Add better support for reporting of tests results.
- Update test runner (`runner.py`) to automatically report the test results for each set of tests.
- Update the CI workflow
  - Make it easier to slice up the plenum tests into smaller chunks.
  - Fix an out of memory error with test report publishing when there are thousands of tests.
  - Update `scacap/action-surefire-report` version
  - Collect the detailed test failure results created by `runner.py` as an artifact so it can be easily reviewed.

Signed-off-by: Wade Barnes <wade.barnes@shaw.ca>

diff --git a/.github/workflows/build.yaml b/.github/workflows/build.yaml
--- a/.github/workflows/build.yaml
+++ b/.github/workflows/build.yaml
@@ -10,7 +10,7 @@ jobs:
       CACHE_KEY_LINT: ${{ steps.cache.outputs.CACHE_KEY_LINT }}
       # Expose the lowercase version of the GitHub repository name
       # to all subsequent jobs that reference image repositories
-      # as the push and pull operations require the URL of the repository 
+      # as the push and pull operations require the URL of the repository
       # to be in lowercase.
       GITHUB_REPOSITORY_NAME: ${{ steps.cache.outputs.GITHUB_REPOSITORY_NAME }}
     steps:
@@ -89,12 +89,19 @@ jobs:
     # Reference to workflow-setup job is required to access the GITHUB_REPOSITORY_NAME output.
     needs: [workflow-setup, build-image]
     runs-on: ubuntu-20.04
+    # Fix for scacap/action-surefire-report out of memory error:
+    # - https://github.com/ScaCap/action-surefire-report/issues/17
+    env:
+      NODE_OPTIONS: '--max_old_space_size=4096'
     container:
       image: ghcr.io/${{ needs.workflow-setup.outputs.GITHUB_REPOSITORY_NAME }}/plenum-build
     strategy:
       matrix:
         module: [plenum]
-        slice: [1, 2, 3]
+        # To slice up the tests into smaller chunks add additional sequential
+        # numbers here.  The subsequent steps will adjust automatically.
+        # ${{ strategy.job-total }} is used to get the total number of slices.
+        slice: [1, 2, 3, 4, 5, 6, 7, 8]
       fail-fast: false
     steps:
       - name: Check out code
@@ -103,15 +110,26 @@ jobs:
       - name: Install dependencies
         run: pip install .[tests]
 
-      - name: Run Indy Plenum ${{ matrix.module }} test slice ${{ matrix.slice }}/3
-        run: RUSTPYTHONASYNCIODEBUG=0 python3 runner.py --pytest "python3 -m pytest -l -vv --junitxml=test-result-plenum-${{ matrix.module }}-${{ matrix.slice }}.xml" --dir "${{ matrix.module }}" --output "test-result-plenum-${{ matrix.slice }}.txt" --test-only-slice "${{ matrix.slice }}/3"
+      - name: Run Indy Plenum ${{ matrix.module }} test slice ${{ matrix.slice }}/${{ strategy.job-total }}
+        id: plenum-test
+        run: RUSTPYTHONASYNCIODEBUG=0 python3 runner.py --pytest "python3 -m pytest -l -vv" --dir "${{ matrix.module }}" --output "test-result-plenum-${{ matrix.slice }}.txt" --test-only-slice "${{ matrix.slice }}/${{ strategy.job-total }}"
 
       - name: Publish Test Report
-        uses: scacap/action-surefire-report@v1
+        if: success() || failure()
+        uses: scacap/action-surefire-report@v1.0.7
         with:
-          check_name: Indy Plenum ${{ matrix.module }} Test Report for slice ${{ matrix.slice }}/3
+          check_name: Indy Plenum ${{ matrix.module }} Test Report for slice ${{ matrix.slice }}/${{ strategy.job-total }}
           github_token: ${{ secrets.GITHUB_TOKEN }}
-          report_paths: test-result-plenum-${{ matrix.module }}-${{ matrix.slice }}.xml
+          report_paths: "*-test-results.xml"
+
+      - name: 'Upload Detailed Test Failure Results'
+        # The test runner only emits the detailed test results if the tests fail.
+        if: (steps.plenum-test.outcome == 'failure') && failure()
+        uses: actions/upload-artifact@v2
+        with:
+          name: detailed-test-result-slice-${{ matrix.slice }}
+          path: test-result-plenum-${{ matrix.slice }}.txt
+          retention-days: 5
 
   indy_plenum:
     name: Indy Plenum Tests
@@ -135,7 +153,7 @@ jobs:
         run: python3 -m pytest -l -vv --junitxml=test-result-plenum-${{ matrix.module }}.xml ${{ matrix.module }}
 
       - name: Publish Test Report
-        uses: scacap/action-surefire-report@v1
+        uses: scacap/action-surefire-report@v1.0.7
         with:
           check_name: Indy Plenum ${{ matrix.module }} Test Report
           github_token: ${{ secrets.GITHUB_TOKEN }}
